import { Key } from 'ts-key-enum';

export enum InputAction {
    UI_LEFT = 'UI_LEFT',
    UI_RIGHT = 'UI_RIGHT',
    UI_UP = 'UI_UP',
    UI_DOWN = 'UI_DOWN',
    UI_OK = 'UI_OK',
    ESCAPE = 'ESCAPE',
    GAME_LEFT = 'GAME_LEFT',
    GAME_RIGHT = 'GAME_RIGHT',
    GAME_JUMP = 'GAME_JUMP',
    GAME_CROUCH = 'GAME_CROUCH',
    GAME_WALK_SLOW = 'GAME_WALK_SLOW',
    GAME_ATTACK1 = 'GAME_ATTACK1',
    GAME_ATTACK2 = 'GAME_ATTACK2',
    GAME_GIFT_NEXT = 'GAME_GIFT_NEXT',
    GAME_GIFT_USE = 'GAME_GIFT_USE',
    GAME_SUICIDE = 'GAME_SUICIDE',
    GAME_PAUSE = 'GAME_PAUSE'
}

