export const TX = {
    
    FONT_PATH: 'font path',
    FONT_SMALL_FONT: 'font small font',
    FONT_BIG_FONT_NORMAL: 'font big font normal',
    FONT_BIG_FONT_HILITE: 'font big font hilite',
    FONT_BIG_FONT_SHADOW: 'font big font shadow',
    
    SETUP_OPTIONS: 'setup options',
    SETUP_VIDEOMODES: 'setup video modes',
    SETUP_MUSIC_AND_SOUNDS: 'setup music & sounds',
    SETUP_MUSIC: 'setup music',
    SETUP_SOUNDS: 'setup sounds',
    SETUP_LANGUAGE: 'setup language',
    SETUP_PLAY: 'setup play',
    SETUP_EXIT: 'setup exit',
    
    INTRO_PRESENTS: 'intro presents',
    INTRO_A_GAME_BY: 'intro a game by',
    INTRO_ORIGINAL: 'intro original character design',
    INTRO_TESTED_BY: 'intro tested by',
    INTRO_THANKS_TO: 'intro thanks to',
    INTRO_TRANSLATION: 'intro translation',
    INTRO_TRANSLATOR: 'intro translator',
    
    MAINMENU_NEW_GAME: 'main menu new game',
    MAINMENU_CONTINUE: 'main menu continue',
    MAINMENU_LOAD_GAME: 'main menu load game',
    MAINMENU_SAVE_GAME: 'main menu save game',
    MAINMENU_CONTROLS: 'main menu controls',
    MAINMENU_GRAPHICS: 'main menu graphics',
    MAINMENU_SOUNDS: 'main menu sounds',
    MAINMENU_EXIT: 'main menu exit game',
    
    MAINMENU_RETURN: 'back to main menu',
    
    LOADGAME_TITLE: 'load menu title',
    LOADGAME_INFO: 'load menu info',
    LOADGAME_EPISODE: 'load menu episode',
    LOADGAME_LEVEL: 'load menu level',
    
    SAVEGAME_TITLE: 'save menu title',
    SAVEGAME_INFO: 'save menu info',
    SAVEGAME_EPISODE: 'save menu episode',
    SAVEGAME_LEVEL: 'save menu level',
    
    CONTROLS_TITLE: 'controls menu title',
    CONTROLS_MOVELEFT: 'controls menu move left',
    CONTROLS_MOVERIGHT: 'controls menu move right',
    CONTROLS_JUMP: 'controls menu jump',
    CONTROLS_DUCK: 'controls menu duck',
    CONTROLS_WALKSLOW: 'controls menu walk slow',
    CONTROLS_EGGATTACK: 'controls menu egg attack',
    CONTROLS_DOODLEATTACK: 'controls menu doodle attack',
    CONTROLS_USEITEM: 'controls menu use item',
    CONTROLS_EDIT: 'controls menu edit',
    CONTROLS_KBDEF: 'controls menu keyboard def',
    CONTROLS_GP4DEF: 'controls menu gamepad4',
    CONTROLS_GP6DEF: 'controls menu gamepad6',
    
    GFX_TITLE: 'graphics menu title',
    GFX_TFX_ON: 'graphics menu transparency fx on',
    GFX_TFX_OFF: 'graphics menu transparency fx off',
    GFX_TMENUS_ON: 'graphics menu menus are transparent',
    GFX_TMENUS_OFF: 'graphics menu menus are not transparent',
    GFX_ITEMS_ON: 'graphics menu item bar is visible',
    GFX_ITEMS_OFF: 'graphics menu item bar is not visible',
    GFX_WEATHER_ON: 'graphics menu weather fx on',
    GFX_WEATHER_OFF: 'graphics menu weather fx off',
    GFX_BGSPRITES_ON: 'graphics menu bg sprites on',
    GFX_BGSPRITES_OFF: 'graphics menu bg sprites off',
    GFX_SPEED_NORMAL: 'graphics menu game speed normal',
    GFX_SPEED_DOUBLE: 'graphics menu game speed double',
    
    SOUND_TITLE: 'sounds menu title',
    SOUND_SFX_VOLUME: 'sounds menu sfx volume',
    SOUND_MUSIC_VOLUME: 'sounds menu music volume',
    SOUND_MORE: 'sounds menu more',
    SOUND_LESS: 'sounds menu less',
    
    PLAYERMENU_TYPE_NAME: 'player screen type your name',
    PLAYERMENU_CONTINUE: 'player screen continue',
    PLAYERMENU_CLEAR: 'player screen clear',
    PLAYER_DEFAULT_NAME: 'player default name',
    
    EPISODES_CHOOSE_EPISODE: 'episode menu choose episode',
    EPISODES_NO_MAPS: 'episode menu no maps',
    EPISODES_GET_MORE: 'episode menu get more episodes at',
    
    MAP_TOTAL_SCORE: 'map screen total score',
    MAP_NEXT_LEVEL: 'map screen next level',
    MAP_EPISODE_BEST_PLAYER: 'episode best player',
    MAP_EPISODE_HISCORE: 'episode hiscore',
    MAP_LEVEL_BEST_PLAYER: 'level best player',
    MAP_LEVEL_HISCORE: 'level hiscore',
    MAP_LEVEL_FASTEST_PLAYER: 'level fastest player',
    MAP_LEVEL_BEST_TIME: 'level best time',
    
    SCORE_SCREEN_TITLE: 'score screen title',
    SCORE_SCREEN_LEVEL_SCORE: 'score screen level score',
    SCORE_SCREEN_BONUS_SCORE: 'score screen bonus score',
    SCORE_SCREEN_TIME_SCORE: 'score screen time score',
    SCORE_SCREEN_ENERGY_SCORE: 'score screen energy score',
    SCORE_SCREEN_ITEM_SCORE: 'score screen item score',
    SCORE_SCREEN_TOTAL_SCORE: 'score screen total score',
    SCORE_SCREEN_NEW_LEVEL_HISCORE: 'score screen new level hiscore',
    SCORE_SCREEN_NEW_LEVEL_BEST_TIME: 'score screen new level best time',
    SCORE_SCREEN_NEW_EPISODE_HISCORE: 'score screen new episode hiscore',
    SCORE_SCREEN_CONTINUE: 'score screen continue',
    
    GAME_SCORE: 'score',
    GAME_TIME: 'game time',
    GAME_ENERGY: 'energy',
    GAME_ITEMS: 'items',
    GAME_ATTACK1: 'attack 1',
    GAME_ATTACK2: 'attack 2',
    GAME_KEYS: 'keys',
    GAME_CLEAR: 'level clear',
    GAME_TIMEBONUS: 'time bonus',
    GAME_KO: 'knocked out',
    GAME_TIMEOUT: 'time out',
    GAME_TRYAGAIN: 'try again',
    GAME_LOCKSOPEN: 'locks open',
    GAME_NEWDOODLE: 'new doodle attack',
    GAME_NEWEGG: 'new egg attack',
    GAME_NEWITEM: 'new item',
    GAME_LOADING: 'loading',
    GAME_PAUSED: 'game paused',
    
    END_CONGRATULATIONS: 'end congratulations',
    END_CHICKENS_SAVED: 'end chickens saved',
    END_THE_END: 'end the end',
    
    INFO01: 'info01',
    INFO02: 'info02',
    INFO03: 'info03',
    INFO04: 'info04',
    INFO05: 'info05',
    INFO06: 'info06',
    INFO07: 'info07',
    INFO08: 'info08',
    INFO09: 'info09',
    INFO10: 'info10',
    INFO11: 'info11',
    INFO12: 'info12',
    INFO13: 'info13',
    INFO14: 'info14',
    INFO15: 'info15',
    INFO16: 'info16',
    INFO17: 'info17',
    INFO18: 'info18',
    INFO19: 'info19',
    
    MAINMENU_LOAD_LANGUAGE: 'load language'
    
};
